export const SIGNUP_ATTEMPT = 'SIGNUP_ATTEMPT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const USER_TYPE = 'USER_TYPE';

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const ACCESS_TOKEN_LOGIN_ATTEMPT = "ACCESS_TOKEN_LOGIN_ATTEMPT";

export const EDIT_PROFILE_ATTEMPT = 'EDIT_PROFILE_ATTEMPT';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';

export const PROFILE_PIC_ATTEMPT = 'PROFILE_PIC_ATTEMPT';
export const PROFILE_PIC_SUCCESS = 'PROFILE_PIC_SUCCESS';
export const PROFILE_PIC_FAIL = 'PROFILE_PIC_FAIL';

export const BANNER_PIC_ATTEMPT = 'BANNER_PIC_ATTEMPT';
export const BANNER_PIC_SUCCESS = 'BANNER_PIC_SUCCESS';
export const BANNER_PIC_FAIL = 'BANNER_PIC_FAIL';

export const PORTFOLIO_PIC_ATTEMPT = 'PORTFOLIO_PIC_ATTEMPT';
export const PORTFOLIO_PIC_SUCCESS = 'PORTFOLIO_PIC_SUCCESS';
export const PORTFOLIO_PIC_FAIL = 'PORTFOLIO_PIC_FAIL';

export const GROUP_PROFILE_PIC_ATTEMPT = 'GROUP_PROFILE_PIC_ATTEMPT';
export const GROUP_PROFILE_PIC_SUCCESS = 'GROUP_PROFILE_PIC_SUCCESS';
export const GROUP_PROFILE_PIC_FAIL = 'GROUP_PROFILE_PIC_FAIL';

export const GET_PROFILE_ATTEMPT = 'GET_PROFILE_ATTEMPT';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const SOCIAL_LOGIN_ATTEMPT = 'SOCIAL_LOGIN_ATTEMPT';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAIL = 'SOCIAL_LOGIN_FAIL';

export const FORGOT_PASSWORD_ATTEMPT = 'FORGOT_PASSWORD_ATTEMPT';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

export const SEARCH_USER_ATTEMPT = 'SEARCH_USER_ATTEMPT';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAIL = 'SEARCH_USER_FAIL';
export const SET_SEARCH_USER_EMPTY = 'SET_SEARCH_USER_EMPTY';

export const GET_USER_PROFILE_ATTEMPT = 'GET_USER_PROFILE_ATTEMPT';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';

export const CREATE_MY_POST_ATTEMPT = 'CREATE_MY_POST_ATTEMPT';
export const CREATE_MY_POST_SUCCESS = 'CREATE_MY_POST_SUCCESS';
export const CREATE_MY_POST_FAIL = 'CREATE_MY_POST_FAIL';

export const EDIT_MY_POST_ATTEMPT = 'EDIT_MY_POST_ATTEMPT';
export const EDIT_MY_POST_SUCCESS = 'EDIT_MY_POST_SUCCESS';
export const EDIT_MY_POST_FAIL = 'EDIT_MY_POST_FAIL';

export const SAHRE_POST_ON_TIMELINE_ATTEMPT = 'SAHRE_POST_ON_TIMELINE_ATTEMPT';
export const SAHRE_POST_ON_TIMELINE_SUCCESS = 'SAHRE_POST_ON_TIMELINE_SUCCESS';
export const SAHRE_POST_ON_TIMELINE_FAIL = 'SAHRE_POST_ON_TIMELINE_FAIL';

export const SAHRE_POST_ON_GROUPS_TIMELINE_ATTEMPT = 'SAHRE_POST_ON_GROUPS_TIMELINE_ATTEMPT';
export const SAHRE_POST_ON_GROUPS_TIMELINE_SUCCESS = 'SAHRE_POST_ON_GROUPS_TIMELINE_SUCCESS';
export const SAHRE_POST_ON_GROUPS_TIMELINE_FAIL = 'SAHRE_POST_ON_GROUPS_TIMELINE_FAIL';

export const GET_MY_POST_ATTEMPT = 'GET_MY_POST_ATTEMPT';
export const GET_MY_POST_SUCCESS = 'GET_MY_POST_SUCCESS';
export const GET_MY_POST_FAIL = 'GET_MY_POST_FAIL';
export const SET_MY_POSTS_LIST_EMPTY = 'SET_MY_POSTS_LIST_EMPTY';

export const UPDATE_MY_POST = 'UPDATE_MY_POST';

export const DELETE_MY_POST_ATTEMPT = 'DELETE_MY_POST_ATTEMPT';
export const DELETE_MY_POST_SUCCESS = 'DELETE_MY_POST_SUCCESS';
export const DELETE_MY_POST_FAIL = 'DELETE_MY_POST_FAIL';

export const SEND_FRIEND_REQUEST_ATTEMPT = 'SEND_FRIEND_REQUEST_ATTEMPT';
export const SEND_FRIEND_REQUEST_SUCCESS = 'SEND_FRIEND_REQUEST_SUCCESS';
export const SEND_FRIEND_REQUEST_FAIL = 'SEND_FRIEND_REQUEST_FAIL';

export const VERIFY_OTP_ATTEMPT = 'VERIFY_OTP_ATTEMPT';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';

export const RESET_PASSWORD_ATTEMPT = 'RESET_PASSWORD_ATTEMPT';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const CHANGE_PASSWORD_ATTEMPT = 'CHANGE_PASSWORD_ATTEMPT';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const LOGOUT_ATTEMPT = 'LOGOUT_ATTEMPT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GET_FRIEND_LIST_ATTEMPT = 'GET_FRIEND_LIST_ATTEMPT';
export const GET_FRIEND_LIST_SUCCESS = 'GET_FRIEND_LIST_SUCCESS';
export const GET_FRIEND_LIST_FAIL = 'GET_FRIEND_LIST_FAIL';
export const SET_MY_FRIENDS_LIST_EMPTY = 'SET_MY_FRIENDS_LIST_EMPTY';

export const GET_FRIEND_COMING_REQUESTS_LIST_ATTEMPT =
  'GET_FRIEND_COMING_REQUESTS_LIST_ATTEMPT';
export const GET_FRIEND_COMING_REQUESTS_LIST_SUCCESS =
  'GET_FRIEND_COMING_REQUESTS_LIST_SUCCESS';
export const GET_FRIEND_COMING_REQUESTS_LIST_FAIL =
  'GET_FRIEND_COMING_REQUESTS_LIST_FAIL';
export const SET_COMING_REQUESTS_EMPTY = 'SET_COMING_REQUESTS_EMPTY';

export const GET_FRIEND_OUTGOING_REQUESTS_LIST_ATTEMPT =
  'GET_FRIEND_OUTGOING_REQUESTS_LIST_ATTEMPT';
export const GET_FRIEND_OUTGOING_REQUESTS_LIST_SUCCESS =
  'GET_FRIEND_OUTGOING_REQUESTS_LIST_SUCCESS';
export const GET_FRIEND_OUTGOING_REQUESTS_LIST_FAIL =
  'GET_FRIEND_OUTGOING_REQUESTS_LIST_FAIL';
export const SET_SENT_REQUESTS_USER_EMPTY = 'SET_SENT_REQUESTS_USER_EMPTY';

export const ACCEPT_FRIEND_REQUEST_ATTEMPT = 'ACCEPT_FRIEND_REQUEST_ATTEMPT';
export const ACCEPT_FRIEND_REQUEST_SUCCESS = 'ACCEPT_FRIEND_REQUEST_SUCCESS';
export const ACCEPT_FRIEND_REQUEST_FAIL = 'ACCEPT_FRIEND_REQUEST_FAIL';

export const MY_POST_LIKE_ATTEMPT = 'MY_POST_LIKE_ATTEMPT';
export const MY_POST_LIKE_SUCCESS = 'MY_POST_LIKE_SUCCESS';
export const MY_POST_LIKE_FAIL = 'MY_POST_LIKE_FAIL';

export const MY_POST_DISLIKE_ATTEMPT = 'MY_POST_DISLIKE_ATTEMPT';
export const MY_POST_DISLIKE_SUCCESS = 'MY_POST_DISLIKE_SUCCESS';
export const MY_POST_DISLIKE_FAIL = 'MY_POST_DISLIKE_FAIL';

export const REJECT_FRIEND_REQUEST_ATTEMPT = 'REJECT_FRIEND_REQUEST_ATTEMPT';
export const REJECT_FRIEND_REQUEST_SUCCESS = 'REJECT_FRIEND_REQUEST_SUCCESS';
export const REJECT_FRIEND_REQUEST_FAIL = 'REJECT_FRIEND_REQUEST_FAIL';

export const REJECT_SEND_FRIEND_REQUEST_ATTEMPT =
  'REJECT_SEND_FRIEND_REQUEST_ATTEMPT';
export const REJECT_SEND_FRIEND_REQUEST_SUCCESS =
  'REJECT_SEND_FRIEND_REQUEST_SUCCESS';
export const REJECT_SEND_FRIEND_REQUEST_FAIL =
  'REJECT_SEND_FRIEND_REQUEST_FAIL';

export const MY_COMMENT_ON_MY_POSTS_ATTEMPT = 'MY_COMMENT_ON_MY_POSTS_ATTEMPT';
export const MY_COMMENT_ON_MY_POSTS_SUCCESS = 'MY_COMMENT_ON_MY_POSTS_SUCCESS';
export const MY_COMMENT_ON_MY_POSTS_FAIL = 'MY_COMMENT_ON_MY_POSTS_FAIL';

export const GET_MY_COMMENT_ON_MY_POSTS_ATTEMPT =
  'GET_MY_COMMENT_ON_MY_POSTS_ATTEMPT';
export const GET_MY_COMMENT_ON_MY_POSTS_SUCCESS =
  'GET_MY_COMMENT_ON_MY_POSTS_SUCCESS';
export const COMMENT_ADD_DELETE_SUCCESS =
  'COMMENT_ADD_DELETE_SUCCESS';
export const GET_MY_COMMENT_ON_MY_POSTS_FAIL =
  'GET_MY_COMMENT_ON_MY_POSTS_FAIL';

export const GET_ANOTHER_USER_POST_ATTEMPT = 'GET_ANOTHER_USER_POST_ATTEMPT';
export const GET_ANOTHER_USER_POST_SUCCESS = 'GET_ANOTHER_USER_POST_SUCCESS';
export const GET_ANOTHER_USER_POST_FAIL = 'GET_ANOTHER_USER_POST_FAIL';
export const SET_ANOTHER_USER_POSTS_EMPTY = 'SET_ANOTHER_USER_POSTS_EMPTY';

export const GET_ALL_USER_POST_ATTEMPT = 'GET_ALL_USER_POST_ATTEMPT';
export const GET_ALL_USER_POST_SUCCESS = 'GET_ALL_USER_POST_SUCCESS';
export const GET_ALL_USER_POST_FAIL = 'GET_ALL_USER_POST_FAIL';
export const SET_ALL_POSTS_EMPTY = 'SET_ALL_POSTS_EMPTY';

export const GET_PUBLIC_POST_ATTEMPT = 'GET_PUBLIC_POST_ATTEMPT';
export const GET_PUBLIC_POST_SUCCESS = 'GET_PUBLIC_POST_SUCCESS';
export const GET_PUBLIC_POST_FAIL = 'GET_PUBLIC_POST_FAIL';
export const SET_PUBLIC_POSTS_EMPTY = 'SET_PUBLIC_POSTS_EMPTY';

export const DELETE_COMMENT_ATTEMPT = 'DELETE_COMMENT_ATTEMPT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const SEND_TEXT_MESSAGE_ATTEMPT = 'SEND_TEXT_MESSAGE_ATTEMPT';
export const SEND_TEXT_MESSAGE_SUCCESS = 'SEND_TEXT_MESSAGE_SUCCESS';
export const SEND_TEXT_MESSAGE_FAIL = 'SEND_TEXT_MESSAGE_FAIL';

export const GET_TEXT_MESSAGE_ATTEMPT = 'GET_TEXT_MESSAGE_ATTEMPT';
export const GET_TEXT_MESSAGE_SUCCESS = 'GET_TEXT_MESSAGE_SUCCESS';
export const GET_TEXT_MESSAGE_FAIL = 'GET_TEXT_MESSAGE_FAIL';

export const CHAT_MEDIA_MESSAGE_ATTEMPT = 'CHAT_MEDIA_MESSAGE_ATTEMPT';
export const CHAT_MEDIA_MESSAGE_SUCCESS = 'CHAT_MEDIA_MESSAGE_SUCCESS';
export const CHAT_MEDIA_MESSAGE_FAIL = 'CHAT_MEDIA_MESSAGE_FAIL';

export const SAVE_TOKEN = 'SAVE_TOKEN';

export const CHATING_WITH_USER_ID_SUCCESS = 'CHATING_WITH_USER_ID_SUCCESS';
export const CHATING_WITH_USER_ID_EMPTY = 'CHATING_WITH_USER_ID_EMPTY';

export const SET_CALL_STATUS = "SET_CALL_STATUS";

export const NAVIGATION_PROPS_SUCCESS = "NAVIGATION_PROPS_SUCCESS";

export const GET_NOTIFICATION_ATTEMPT = 'GET_NOTIFICATION_ATTEMPT';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_FAIL = 'GET_NOTIFICATION_FAIL';
export const GET_NOTIFICATION_COUNT_RESET = 'GET_NOTIFICATION_COUNT_RESET';
export const GET_NOTIFICATION_LIST_EMPTY = 'GET_NOTIFICATION_LIST_EMPTY';

export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS';

export const GET_CHAT_NOTIFICATION_SUCCESS = 'GET_CHAT_NOTIFICATION_SUCCESS';
export const DELETE_CHAT_NOTIFICATION_SUCCESS = 'DELETE_CHAT_NOTIFICATION_SUCCESS';

export const CREATE_GROUP_ATTEMPT = 'CREATE_GROUP_ATTEMPT';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL';

export const GET_GROUPS_LIST_ATTEMPT = 'GET_GROUPS_LIST_ATTEMPT';
export const GET_GROUPS_LIST_SUCCESS = 'GET_GROUPS_LIST_SUCCESS';
export const GET_GROUPS_LIST_FAIL = 'GET_GROUPS_LIST_FAIL';

export const DELETE_GROUP_ATTEMPT = 'DELETE_GROUP_ATTEMPT';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL';

export const GET_GROUPS_MEMBERS_ATTEMPT = 'GET_GROUPS_MEMBERS_ATTEMPT';
export const GET_GROUPS_MEMBERS_SUCCESS = 'GET_GROUPS_MEMBERS_SUCCESS';
export const GET_GROUPS_MEMBERS_FAIL = 'GET_GROUPS_MEMBERS_FAIL';
export const GROUPS_MEMBERS_LIST_EMPTY = 'GROUPS_MEMBERS_LIST_EMPTY';

export const ADD_GROUPS_MEMBERS_ATTEMPT = 'ADD_GROUPS_MEMBERS_ATTEMPT';
export const ADD_GROUPS_MEMBERS_SUCCESS = 'ADD_GROUPS_MEMBERS_SUCCESS';
export const ADD_GROUPS_MEMBERS_FAIL = 'ADD_GROUPS_MEMBERS_FAIL';

export const CREATE_GROUP_POST_ATTEMPT = 'CREATE_GROUP_POST_ATTEMPT';
export const CREATE_GROUP_POST_SUCCESS = 'CREATE_GROUP_POST_SUCCESS';
export const CREATE_GROUP_POST_FAIL = 'CREATE_GROUP_POST_FAIL';

export const GET_GROUP_POST_ATTEMPT = 'GET_GROUP_POST_ATTEMPT';
export const GET_GROUP_POST_SUCCESS = 'GET_GROUP_POST_SUCCESS';
export const GET_GROUP_POST_FAIL = 'GET_GROUP_POST_FAIL';
export const GROUP_POSTS_EMPTY = "GROUP_POSTS_EMPTY";
export const GROUPS_LIST_EMPTY = 'GROUPS_LIST_EMPTY';

export const DELETE_GROUPS_MEMBERS_ATTEMPT = 'DELETE_GROUPS_MEMBERS_ATTEMPT';
export const DELETE_GROUPS_MEMBERS_SUCCESS = 'DELETE_GROUPS_MEMBERS_SUCCESS';
export const DELETE_GROUPS_MEMBERS_FAIL = 'DELETE_GROUPS_MEMBERS_FAIL';

export const LEFT_GROUPS_ATTEMPT = 'LEFT_GROUPS_ATTEMPT';
export const LEFT_GROUPS_SUCCESS = 'LEFT_GROUPS_SUCCESS';
export const LEFT_GROUPS_FAIL = 'LEFT_GROUPS_FAIL';

export const READ_NOTIFICATION_ATTEMPT = 'READ_NOTIFICATION_ATTEMPT';
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';
export const READ_NOTIFICATION_FAIL = 'READ_NOTIFICATION_FAIL';

export const DELETE_NOTIFICATION_ATTEMPT = 'DELETE_NOTIFICATION_ATTEMPT';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';

export const VIEW_ALL_NOTIFICATION_ATTEMPT = 'VIEW_ALL_NOTIFICATION_ATTEMPT';
export const VIEW_ALL_NOTIFICATION_SUCCESS = 'VIEW_ALL_NOTIFICATION_SUCCESS';
export const VIEW_ALL_NOTIFICATION_FAIL = 'VIEW_ALL_NOTIFICATION_FAIL';

export const CHECK_POST_FOR_LIKE_UNLIKE_COMMENT_ATTEMPT = 'CHECK_POST_FOR_LIKE_UNLIKE_COMMENT_ATTEMPT';

export const REPORT_POST_ATTEMPT = 'REPORT_POST_ATTEMPT';
export const REPORT_POST_SUCCESS = 'REPORT_POST_SUCCESS';
export const REPORT_POST_FAIL = 'REPORT_POST_FAIL';

export const REPORT_SMS_ATTEMPT = 'REPORT_SMS_ATTEMPT';
export const REPORT_SMS_SUCCESS = 'REPORT_SMS_SUCCESS';
export const REPORT_SMS_FAIL = 'REPORT_SMS_FAIL';

export const MAKE_USER_FRIEND_WITH_ADMIN_ATTEMPT = 'MAKE_USER_FRIEND_WITH_ADMIN_ATTEMPT';
export const MAKE_USER_FRIEND_WITH_ADMIN_SUCCESS = 'MAKE_USER_FRIEND_WITH_ADMIN_SUCCESS';
export const MAKE_USER_FRIEND_WITH_ADMIN_FAIL = 'MAKE_USER_FRIEND_WITH_ADMIN_FAIL';

export const SUBMIT_PHONE_NUMBERS_FOR_FRIENDS_SUGGESTION_ATTEMPT = 'SUBMIT_PHONE_NUMBERS_FOR_FRIENDS_SUGGESTION_ATTEMPT';
export const SUBMIT_PHONE_NUMBERS_FOR_FRIENDS_SUGGESTION_SUCCESS = 'SUBMIT_PHONE_NUMBERS_FOR_FRIENDS_SUGGESTION_SUCCESS';
export const SUBMIT_PHONE_NUMBERS_FOR_FRIENDS_SUGGESTION_FAIL = 'SUBMIT_PHONE_NUMBERS_FOR_FRIENDS_SUGGESTION_FAIL';

export const GET_SUGGESTION_ATTEMPT = 'GET_SUGGESTION_ATTEMPT';
export const GET_SUGGESTION_SUCCESS = 'GET_SUGGESTION_SUCCESS';
export const GET_SUGGESTION_FAIL = 'GET_SUGGESTION_FAIL';
export const GET_SUGGESTION_EMPTY = 'GET_SUGGESTION_EMPTY';

export const MARKET_PLACE_ATTEMPT = 'MARKET_PLACE_ATTEMPT';
export const MARKET_PLACE_SUCCESS = 'MARKET_PLACE_SUCCESS';
export const MARKET_PLACE_FAIL = 'MARKET_PLACE_FAIL';
export const MARKET_PLACE_LIST_EMPTY = 'MARKET_PLACE_LIST_EMPTY';

export const MARKET_PLACE_CATEGORY_ATTEMPT = 'MARKET_PLACE_CATEGORY_ATTEMPT';
export const MARKET_PLACE_CATEGORY_SUCCESS = 'MARKET_PLACE_CATEGORY_SUCCESS';
export const MARKET_PLACE_CATEGORY_FAIL = 'MARKET_PLACE_CATEGORY_FAIL';

export const UNFRIEND_ATTEMPT = 'UNFRIEND_ATTEMPT';
export const UNFRIEND_SUCCESS = 'UNFRIEND_SUCCESS';
export const UNFRIEND_FAIL = 'UNFRIEND_FAIL';

export const GET_APP_VERSION_ATTEMPT = 'GET_APP_VERSION_ATTEMPT';
export const GET_APP_VERSION_SUCCESS = 'GET_APP_VERSION_SUCCESS';
export const GET_APP_VERSION_FAIL = 'GET_APP_VERSION_FAIL';

export const UNREPORT_POST_SUCCESS = "UNREPORT_POST_SUCCESS";

export const GET_GROUPS_LIST_FOR_JOIN_ATTEMPT = 'GET_GROUPS_LIST_FOR_JOIN_ATTEMPT';
export const GET_GROUPS_LIST_FOR_JOIN_SUCCESS = 'GET_GROUPS_LIST_FOR_JOIN_SUCCESS';
export const GET_GROUPS_LIST_FOR_JOIN_FAIL = 'GET_GROUPS_LIST_FOR_JOIN_FAIL';
export const GET_GROUPS_LIST_FOR_JOIN_EMPTY = 'GET_GROUPS_LIST_FOR_JOIN_EMPTY';

export const REQUEST_SEND_FOR_JOIN_GROUP_ATTEMPT = 'REQUEST_SEND_FOR_JOIN_GROUP_ATTEMPT';
export const REQUEST_SEND_FOR_JOIN_GROUP_SUCCESS = 'REQUEST_SEND_FOR_JOIN_GROUP_SUCCESS';
export const REQUEST_SEND_FOR_JOIN_GROUP_FAIL = 'REQUEST_SEND_FOR_JOIN_GROUP_FAIL';

export const REQUEST_CANCEL_FOR_JOIN_GROUP_ATTEMPT = 'REQUEST_CANCEL_FOR_JOIN_GROUP_ATTEMPT';
export const REQUEST_CANCEL_FOR_JOIN_GROUP_SUCCESS = 'REQUEST_CANCEL_FOR_JOIN_GROUP_SUCCESS';
export const REQUEST_CANCEL_FOR_JOIN_GROUP_FAIL = 'REQUEST_CANCEL_FOR_JOIN_GROUP_FAIL';

export const GROUP_REQUEST_ATTEMPT = 'GROUP_REQUEST_ATTEMPT';
export const GROUP_REQUEST_SUCCESS = 'GROUP_REQUEST_SUCCESS';
export const GROUP_REQUEST_FAIL = 'GROUP_REQUEST_FAIL';

export const GROUP_REQUEST_ACCEPT_ATTEMPT = 'GROUP_REQUEST_ACCEPT_ATTEMPT';
export const GROUP_REQUEST_ACCEPT_SUCCESS = 'GROUP_REQUEST_ACCEPT_SUCCESS';
export const GROUP_REQUEST_ACCEPT_FAIL = 'GROUP_REQUEST_ACCEPT_FAIL';

export const GROUP_REQUEST_DELETE_ATTEMPT = 'GROUP_REQUEST_DELETE_ATTEMPT';
export const GROUP_REQUEST_DELETE_SUCCESS = 'GROUP_REQUEST_DELETE_SUCCESS';
export const GROUP_REQUEST_DELETE_FAIL = 'GROUP_REQUEST_DELETE_FAIL';

export const IS_USER_HAVE_PLAN = 'IS_USER_HAVE_PLAN';
